import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

/**
 * Builds the content of the auto-generated registry file that collects external template entries.
 *
 * @param importSection - Generated import statements for each convention file
 * @param entriesLiteral - Generated array literal entries
 * @returns Source code string written to pdf-generators.generated.ts
 */
function buildOutput({ importSection, entriesLiteral }: { importSection: string; entriesLiteral: string }): string {
  return `// AUTO-GENERATED by mercato generate registry
import type { TemplateEntry } from '@open-mercato/pdf-generators/modules/pdf_generators/lib/interfaces'
${importSection ? `\n${importSection}\n` : ''}
export const pdfGeneratorTemplateEntries: Array<{ entity: string; templates: TemplateEntry[] }> = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`
}

const pdfGeneratorsPlugin: GeneratorPlugin = {
  id: 'pdf-generators.templates',
  conventionFile: 'pdf-generators.ts',
  importPrefix: 'PDF_GENERATORS_TEMPLATES',
  configExpr: (importName: string, entity: string) =>
    `{ entity: '${entity}', templates: ((${importName}.default ?? ${importName}.templates ?? []) as TemplateEntry[]) }`,
  outputFileName: 'pdf-generators.generated.ts',
  buildOutput,
  bootstrapRegistration: {
    entriesExportName: 'pdfGeneratorTemplateEntries',
    registrationImports: [
      `import { templateRegistry } from '@open-mercato/pdf-generators/modules/pdf_generators/lib/template-registry'`,
    ],
    buildCall: (name: string) =>
      `templateRegistry.registerExternal(${name}.flatMap((e) => e.templates))`,
  },
}

/** Generator plugins consumed by `mercato generate registry` to produce the external template registry file. */
export const generatorPlugins: GeneratorPlugin[] = [pdfGeneratorsPlugin]

export default generatorPlugins
