export type CurrencyInfo = { code: string; name: string }

/** ISO 4217 active currency and funds codes (alpha-3) with English names. */
export const CURRENCY_CODES: readonly CurrencyInfo[] = [
  { code: 'AED', name: 'United Arab Emirates dirham' },
  { code: 'AFN', name: 'Afghan afghani' },
  { code: 'ALL', name: 'Albanian lek' },
  { code: 'AMD', name: 'Armenian dram' },
  { code: 'AOA', name: 'Angolan kwanza' },
  { code: 'ARS', name: 'Argentine peso' },
  { code: 'AUD', name: 'Australian dollar' },
  { code: 'AWG', name: 'Aruban florin' },
  { code: 'AZN', name: 'Azerbaijani manat' },
  { code: 'BAM', name: 'Bosnia and Herzegovina convertible mark' },
  { code: 'BBD', name: 'Barbados dollar' },
  { code: 'BDT', name: 'Bangladeshi taka' },
  { code: 'BGN', name: 'Bulgarian lev' },
  { code: 'BHD', name: 'Bahraini dinar' },
  { code: 'BIF', name: 'Burundian franc' },
  { code: 'BMD', name: 'Bermudian dollar' },
  { code: 'BND', name: 'Brunei dollar' },
  { code: 'BOB', name: 'Bolivian boliviano' },
  { code: 'BOV', name: 'Bolivian Mvdol' },
  { code: 'BRL', name: 'Brazilian real' },
  { code: 'BSD', name: 'Bahamian dollar' },
  { code: 'BTN', name: 'Bhutanese ngultrum' },
  { code: 'BWP', name: 'Botswana pula' },
  { code: 'BYN', name: 'Belarusian ruble' },
  { code: 'BZD', name: 'Belize dollar' },
  { code: 'CAD', name: 'Canadian dollar' },
  { code: 'CDF', name: 'Congolese franc' },
  { code: 'CHE', name: 'WIR euro' },
  { code: 'CHF', name: 'Swiss franc' },
  { code: 'CHW', name: 'WIR franc' },
  { code: 'CLF', name: 'Unidad de Fomento' },
  { code: 'CLP', name: 'Chilean peso' },
  { code: 'CNY', name: 'Chinese yuan' },
  { code: 'COP', name: 'Colombian peso' },
  { code: 'COU', name: 'Unidad de Valor Real' },
  { code: 'CRC', name: 'Costa Rican colon' },
  { code: 'CUP', name: 'Cuban peso' },
  { code: 'CVE', name: 'Cape Verdean escudo' },
  { code: 'CZK', name: 'Czech koruna' },
  { code: 'DJF', name: 'Djiboutian franc' },
  { code: 'DKK', name: 'Danish krone' },
  { code: 'DOP', name: 'Dominican peso' },
  { code: 'DZD', name: 'Algerian dinar' },
  { code: 'EGP', name: 'Egyptian pound' },
  { code: 'ERN', name: 'Eritrean nakfa' },
  { code: 'ETB', name: 'Ethiopian birr' },
  { code: 'EUR', name: 'Euro' },
  { code: 'FJD', name: 'Fiji dollar' },
  { code: 'FKP', name: 'Falkland Islands pound' },
  { code: 'GBP', name: 'Pound sterling' },
  { code: 'GEL', name: 'Georgian lari' },
  { code: 'GHS', name: 'Ghanaian cedi' },
  { code: 'GIP', name: 'Gibraltar pound' },
  { code: 'GMD', name: 'Gambian dalasi' },
  { code: 'GNF', name: 'Guinean franc' },
  { code: 'GTQ', name: 'Guatemalan quetzal' },
  { code: 'GYD', name: 'Guyanese dollar' },
  { code: 'HKD', name: 'Hong Kong dollar' },
  { code: 'HNL', name: 'Honduran lempira' },
  { code: 'HTG', name: 'Haitian gourde' },
  { code: 'HUF', name: 'Hungarian forint' },
  { code: 'IDR', name: 'Indonesian rupiah' },
  { code: 'ILS', name: 'Israeli new shekel' },
  { code: 'INR', name: 'Indian rupee' },
  { code: 'IQD', name: 'Iraqi dinar' },
  { code: 'IRR', name: 'Iranian rial' },
  { code: 'ISK', name: 'Icelandic krona' },
  { code: 'JMD', name: 'Jamaican dollar' },
  { code: 'JOD', name: 'Jordanian dinar' },
  { code: 'JPY', name: 'Japanese yen' },
  { code: 'KES', name: 'Kenyan shilling' },
  { code: 'KGS', name: 'Kyrgyzstani som' },
  { code: 'KHR', name: 'Cambodian riel' },
  { code: 'KMF', name: 'Comorian franc' },
  { code: 'KPW', name: 'North Korean won' },
  { code: 'KRW', name: 'South Korean won' },
  { code: 'KWD', name: 'Kuwaiti dinar' },
  { code: 'KYD', name: 'Cayman Islands dollar' },
  { code: 'KZT', name: 'Kazakhstani tenge' },
  { code: 'LAK', name: 'Lao kip' },
  { code: 'LBP', name: 'Lebanese pound' },
  { code: 'LKR', name: 'Sri Lankan rupee' },
  { code: 'LRD', name: 'Liberian dollar' },
  { code: 'LSL', name: 'Lesotho loti' },
  { code: 'LYD', name: 'Libyan dinar' },
  { code: 'MAD', name: 'Moroccan dirham' },
  { code: 'MDL', name: 'Moldovan leu' },
  { code: 'MGA', name: 'Malagasy ariary' },
  { code: 'MKD', name: 'Macedonian denar' },
  { code: 'MMK', name: 'Myanmar kyat' },
  { code: 'MNT', name: 'Mongolian togrog' },
  { code: 'MOP', name: 'Macanese pataca' },
  { code: 'MRU', name: 'Mauritanian ouguiya' },
  { code: 'MUR', name: 'Mauritian rupee' },
  { code: 'MVR', name: 'Maldivian rufiyaa' },
  { code: 'MWK', name: 'Malawian kwacha' },
  { code: 'MXN', name: 'Mexican peso' },
  { code: 'MXV', name: 'Mexican Unidad de Inversion' },
  { code: 'MYR', name: 'Malaysian ringgit' },
  { code: 'MZN', name: 'Mozambican metical' },
  { code: 'NAD', name: 'Namibian dollar' },
  { code: 'NGN', name: 'Nigerian naira' },
  { code: 'NIO', name: 'Nicaraguan cordoba' },
  { code: 'NOK', name: 'Norwegian krone' },
  { code: 'NPR', name: 'Nepalese rupee' },
  { code: 'NZD', name: 'New Zealand dollar' },
  { code: 'OMR', name: 'Omani rial' },
  { code: 'PAB', name: 'Panamanian balboa' },
  { code: 'PEN', name: 'Peruvian sol' },
  { code: 'PGK', name: 'Papua New Guinean kina' },
  { code: 'PHP', name: 'Philippine peso' },
  { code: 'PKR', name: 'Pakistani rupee' },
  { code: 'PLN', name: 'Polish zloty' },
  { code: 'PYG', name: 'Paraguayan guarani' },
  { code: 'QAR', name: 'Qatari riyal' },
  { code: 'RON', name: 'Romanian leu' },
  { code: 'RSD', name: 'Serbian dinar' },
  { code: 'RUB', name: 'Russian ruble' },
  { code: 'RWF', name: 'Rwandan franc' },
  { code: 'SAR', name: 'Saudi riyal' },
  { code: 'SBD', name: 'Solomon Islands dollar' },
  { code: 'SCR', name: 'Seychelles rupee' },
  { code: 'SDG', name: 'Sudanese pound' },
  { code: 'SEK', name: 'Swedish krona' },
  { code: 'SGD', name: 'Singapore dollar' },
  { code: 'SHP', name: 'Saint Helena pound' },
  { code: 'SLE', name: 'Sierra Leonean leone' },
  { code: 'SOS', name: 'Somali shilling' },
  { code: 'SRD', name: 'Surinamese dollar' },
  { code: 'SSP', name: 'South Sudanese pound' },
  { code: 'STN', name: 'Sao Tome and Principe dobra' },
  { code: 'SVC', name: 'Salvadoran colon' },
  { code: 'SYP', name: 'Syrian pound' },
  { code: 'SZL', name: 'Swazi lilangeni' },
  { code: 'THB', name: 'Thai baht' },
  { code: 'TJS', name: 'Tajikistani somoni' },
  { code: 'TMT', name: 'Turkmenistan manat' },
  { code: 'TND', name: 'Tunisian dinar' },
  { code: 'TOP', name: "Tongan pa'anga" },
  { code: 'TRY', name: 'Turkish lira' },
  { code: 'TTD', name: 'Trinidad and Tobago dollar' },
  { code: 'TWD', name: 'New Taiwan dollar' },
  { code: 'TZS', name: 'Tanzanian shilling' },
  { code: 'UAH', name: 'Ukrainian hryvnia' },
  { code: 'UGX', name: 'Ugandan shilling' },
  { code: 'USD', name: 'United States dollar' },
  { code: 'USN', name: 'United States dollar (next day)' },
  { code: 'UYI', name: 'Uruguay Peso en Unidades Indexadas' },
  { code: 'UYU', name: 'Uruguayan peso' },
  { code: 'UYW', name: 'Unidad previsional' },
  { code: 'UZS', name: 'Uzbekistani som' },
  { code: 'VED', name: 'Venezuelan digital bolivar' },
  { code: 'VES', name: 'Venezuelan sovereign bolivar' },
  { code: 'VND', name: 'Vietnamese dong' },
  { code: 'VUV', name: 'Vanuatu vatu' },
  { code: 'WST', name: 'Samoan tala' },
  { code: 'XAD', name: 'Arab Accounting Dinar' },
  { code: 'XAF', name: 'CFA franc BEAC' },
  { code: 'XAG', name: 'Silver (one troy ounce)' },
  { code: 'XAU', name: 'Gold (one troy ounce)' },
  { code: 'XBA', name: 'European Composite Unit' },
  { code: 'XBB', name: 'European Monetary Unit' },
  { code: 'XBC', name: 'European Unit of Account 9' },
  { code: 'XBD', name: 'European Unit of Account 17' },
  { code: 'XCD', name: 'East Caribbean dollar' },
  { code: 'XCG', name: 'Caribbean guilder' },
  { code: 'XDR', name: 'Special drawing rights' },
  { code: 'XOF', name: 'CFA franc BCEAO' },
  { code: 'XPD', name: 'Palladium (one troy ounce)' },
  { code: 'XPF', name: 'CFP franc' },
  { code: 'XPT', name: 'Platinum (one troy ounce)' },
  { code: 'XSU', name: 'SUCRE' },
  { code: 'XUA', name: 'ADB Unit of Account' },
  { code: 'YER', name: 'Yemeni rial' },
  { code: 'ZAR', name: 'South African rand' },
  { code: 'ZMW', name: 'Zambian kwacha' },
  { code: 'ZWG', name: 'Zimbabwe Gold' },
] as const

const COMMON_CURRENCY_CODES = ['PLN', 'EUR', 'USD', 'GBP', 'CHF', 'CZK'] as const
const COMMON_CURRENCY_CODE_SET = new Set<string>(COMMON_CURRENCY_CODES)
const CURRENCY_CODE_SET = new Set(CURRENCY_CODES.map((currency) => currency.code))

/** True when `code` (case-insensitive) is a valid ISO-4217 code present in CURRENCY_CODES. */
export function isValidCurrencyCode(code: string | null | undefined): boolean {
  const normalized = (code ?? '').trim().toUpperCase()
  return CURRENCY_CODE_SET.has(normalized)
}

/** Options for a ComboboxInput. value = code, label = `${code} — ${name}`. */
export function searchCurrencies(
  query: string | null | undefined,
  limit = 50,
): Array<{ value: string; label: string }> {
  const max = Number.isFinite(limit) ? Math.max(0, Math.floor(limit)) : 50
  if (max === 0) return []

  const needle = (query ?? '').trim().toLowerCase()
  const source = needle
    ? CURRENCY_CODES.filter(
        (currency) => currency.code.toLowerCase().includes(needle) || currency.name.toLowerCase().includes(needle),
      )
    : [
        ...COMMON_CURRENCY_CODES.map((code) => CURRENCY_CODES.find((currency) => currency.code === code)).filter(
          (currency): currency is CurrencyInfo => Boolean(currency),
        ),
        ...CURRENCY_CODES.filter((currency) => !COMMON_CURRENCY_CODE_SET.has(currency.code)),
      ]

  return source.slice(0, max).map((currency) => ({ value: currency.code, label: `${currency.code} — ${currency.name}` }))
}
